os: linux
dist: focal

language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

jobs:
  include:
    - name: module
      install: npm ci
      script: npm run test

    - name: typescript
      script: |
        cd test-types
        npm ci
        npm run test
